### ISSUE TITLE
PUID PGID 设为33(www-data 用户) 无法启动

### ISSUE THREAD

**Issue by xiaoyan-ms** [sanjusss/aria2-ariang-docker#10]
为了在nextcloud中挂在aria2目录作为外部存储，并且拥有删除权限，希望把aria的data目录改为用户www-data
创建容器时使用参数
-e PUID=33 \
-e PGID=33 \

docker logs 的部分日志：

addgroup: gid '33' in use
adduser: unknown group aria2
sudo: unknown user: aria2
sudo: unable to initialize policy plugin

**Comment by sanjusss** [comment]
试试最新的镜像。应该解决了这个问题。
