### ISSUE TITLE
请问web-ui界面（AriaNg）如何关闭用户认证，直接访问？

### ISSUE THREAD

**Issue by 518512** [sanjusss/aria2-ariang-docker#5]
请问web-ui界面（AriaNg）如何关闭用户认证，直接访问？

谢谢

**Comment by sanjusss** [comment]
这个镜像暂时不能做到。你可以设置简单密码，或用浏览器记住密码

**Comment by 518512** [comment]
> 这个镜像暂时不能做到。你可以设置简单密码，或用浏览器记住密码

好的，谢谢！期待后期可以支持。

还有是否可以考虑，把aria2 rpc端口也设置成，其他软件可以连接。

毕竟 ariang 是网页端，使用比较方便。 手机端还是使用类似transdone这样的app方便。

**Comment by sanjusss** [comment]
更新镜像到最新版，创建镜像时设置ENABLE_AUTO_RANDOM_ARIA为false（默认值，不设置也可以）。这个rpc端口应该是可以在外部连接的，可以在ariang里查看相关连接参数。  
设置ENABLE_AUTO_RANDOM_ARIA这个环境变量为true后，rpc端口就不能被外部访问了。

**Comment by 518512** [comment]
> 更新镜像到最新版，创建镜像时设置ENABLE_AUTO_RANDOM_ARIA为false（默认值，不设置也可以）。这个rpc端口应该是可以在外部连接的，可以在ariang里查看相关连接参数。
> 设置ENABLE_AUTO_RANDOM_ARIA这个环境变量为true后，rpc端口就不能被外部访问了。

搞定了，重新建立镜像 并把 端口改为 6800 ，transdone就可以连接了。

谢谢
