### ISSUE TITLE
Portainer查看容器显示 healthy，请问是什么原因？

### ISSUE THREAD

**Issue by 518512** [sanjusss/aria2-ariang-docker#6]
查看日志：
02/11 11:24:18 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

建立容器命令：

docker run -d --name=aria2 \
    -p 6800:80 \
    -v /mnt/udisk/FileBrowser/myfiles/:/data \
    -v /mnt/udisk/aria2/conf:/conf \
    -e EXTERNAL_PORT=6800 \
    --restart unless-stopped \
    sanjusss/aria2-ariang-docker

**Comment by 518512** [comment]
还有就是通过日志看，时间好像也是不准的，是不是缺少 -e TZ=Asia/Shanghai \ 的环境变量？

**Comment by sanjusss** [comment]
第一个问题：  
我的镜像出了点问题，现在已经修复。重新拉取下镜像就行。  

第二个问题：  
默认容器为UTC时区，镜像没有设置时区的环境变量。如果你的宿主机时间是你需要的时间，可以简单使用宿主机的时间`-v /etc/localtime:/etc/localtime:ro`。

**Comment by sanjusss** [comment]
明天我加个tz的选项吧

**Comment by 518512** [comment]
> 明天我加个tz的选项吧

好的，谢谢！等着新版上线重新拉一下

**Comment by sanjusss** [comment]
已添加tz
