### ISSUE TITLE
为什么aria2.conf经常被清空呢？

### ISSUE THREAD

**Issue by sunetic** [sanjusss/aria2-ariang-docker#7]
经常重启后无法启动，查了一下发现aria2.conf被清空

**Comment by sanjusss** [comment]
挂载conf文件夹了吗？文件和文件夹是否有读写权限？

**Comment by sunetic** [comment]
挂载的，具有读写权限。就是挂载的那个目录里的aria2.conf总是被清空，奇怪的很

**Comment by sunetic** [comment]
另外顺便问下，web的账号密码可以去掉么，直接访问

**Comment by sanjusss** [comment]
> 另外顺便问下，web的账号密码可以去掉么，直接访问

稍后我增加个密码的开关吧。

> 经常重启后无法启动，查了一下发现aria2.conf被清空

容器的启动命令或启动参数是什么？是重启时才清空，还是过一段时间自动清空？
清空指的是整个文件没有任何内容吧？

**Comment by sanjusss** [comment]
现在增加了ENABLE_PASSWORD变量来关闭密码。

清空设置的问题，我这里无法复现，需要你贴一下启动参数。
