### ISSUE TITLE
AriaNG,每次打开，弹出您还没有进行设置，点击这里进行设置。

### ISSUE THREAD

**Issue by j945** [sanjusss/aria2-ariang-docker#8]
docker 安装在 ubuntu 19 中 ，用Mac， chrome 打开，弹出提示。点击提示后，进到设置界面，设置之后刷新页面，发现修改的内容被还原。

**Comment by sanjusss** [comment]
> ENABLE_AUTO_CLEAR_ARIANG变量默认true，每次访问时会清空浏览器缓存。  

所以启动容器时，设置容器环境变量`ENABLE_AUTO_CLEAR_ARIANG`为`false`即可。

**Comment by j945** [comment]
谢谢，问题已经解决。
